name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_react:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build

  deploy_react:
    name: Deploy React App
    needs: build_react
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  prepare_and_upload_laravel:
    name: Build Laravel
    needs: deploy_react
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP, Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev
        working-directory: ./backend

      - name: Create .env file
        run: |
          touch backend/.env
          echo "APP_ENV=production" >> backend/.env
          echo "APP_DEBUG=false" >> backend/.env
          echo "APP_KEY=" >> backend/.env # APP_KEY will be generated by the php artisan key:generate
          echo "DB_CONNECTION=mysql" >> backend/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> backend/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> backend/.env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> backend/.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> backend/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> backend/.env
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" >> backend/.env

      - name: Deploy Laravel
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.INFINITYFREE_SERVER }}
          username: ${{ secrets.INFINITYFREE_USERNAME }}
          password: ${{ secrets.INFINITYFREE_PASSWORD }}
          local-dir: ./public/
          server-dir: /home/vol9_3/infinityfree.com/ifo_36039644/htdocs/
      
      - name: Check MySQL Database Connection
        run: |
            mysqladmin -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} ping

      - name: Check MySQL Database Detailed Status
        run: |
            mysql -h ${{ secrets.DB_HOST }} -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "STATUS"
